version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.0
    steps:
      - checkout
      - run:
          shell: pwsh
          name: build package
          command: |
            dotnet restore
            $version = "2.0.${env:CIRCLE_BUILD_NUM}";
            $suffix = "-prerelease";
            if($env:CIRCLE_BRANCH -eq "develop")
            {
              $suffix = "-alpha";
            }
            elseif ($env:CIRCLE_BRANCH.Contains("release"))
            {
              $suffix = "-beta";
            }
            
            if($env:CIRCLE_TAG -ne $null)
            {
              $version = $env:CIRCLE_TAG;
              $suffix = "";
            }
            
            $version = $version + $suffix;
            dotnet pack -c release -o . /p:PackageVersion="${version}"
      - store_artifacts:
          path: artifacts
      - persist_to_workspace:
          root: .
          paths:
            - .
  unit-tests:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
          name: run unit tests
          command: |
            dotnet restore
            dotnet test ./SecretReaderTests/SecretReaderTests.csproj
  integration-tests:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
          name: run unit tests
          command: |
            dotnet restore
            dotnet test ./SsmIntegrationTest/SsmIntegrationTest.csproj
          environment:
            SSM_PARAMETER_PATH: /testing
  publish:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - attach_workspace:
          at: .
      - run:
          name: push package
          command: |
            dotnet nuget push -s https://nuget.org -k $nugetapikey *.nupkg
workflows:
  version: 2
  build_and_deploy:
    #TODO: Get rid of the filters in the workflows because they're not being used
    jobs:
      - build:
          filters:
            tags:
              ignore:
                - /destroy/
                - /finish.*/
      - unit-tests:
          requires:
            - build
          filters:
            tags:
              ignore:
                - /destroy/
                - /finish.*/
      - integration-tests:
          requires:
            - build
          filters:
            tags:
              ignore:
                - /destroy/
                - /finish.*/
      - publish:
          requires:
            - build
            - unit-tests
            - integration-tests
          filters:
            tags:
              ignore:
                - /destroy/
                - /finish.*/