version: 2
jobs:
  build_dev:
    working_directory: ~/repo
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
          name: build package
          command: |
            dotnet pack -c release /p:PackageVersion="1.0.${CIRCLE_BUILD_NUM}"
      - store_artifacts:
          path: artifacts
      - persist_to_workspace:
          root: .
          paths:
            - .
  publish:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - attach_workspace:
          at: .
      - run:
          name: push package
          command: |
            dotnet nuget push -s https://nuget.org -k $nugetapikey ./AwsSecretReader/*.nupkg
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_dev:
          filters:
            tags:
              ignore:
                - /destroy/
                - /finish.*/
      - deploy:
          requires:
            - build_dev
          filters:
            tags:
              ignore:
                - /destroy/
                - /finish.*/