version: 2
jobs:
  restore:
    working_directory: ~/repo
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
          name: build package
          command: |
            dotnet restore
      - save-cache:
          paths:
            - /tmp/NugetScratch
            - /root/.nuget/
            - /root/.local/share/NuGet
          key: nuget-cache-{{ .Branch }}
      - store_artifacts:
          path: artifacts
      - persist_to_workspace:
          root: .
          paths:
            - .
  unit-tests:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - restore-cache:
          keys:
            - nuget-cache-{{ .Branch }}
      - checkout
      - run:
          name: run unit tests
          command: |
            dotnet test ./SecretReaderTests/SecretReaderTests.csproj
  integration-tests:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - restore-cache:
          keys:
            - nuget-cache-{{ .Branch }}
      - checkout
      - run:
          name: run unit tests
          command: |
            dotnet restore
            dotnet test ./SsmIntegrationTest/SsmIntegrationTest.csproj
          environment:
            SSM_PARAMETER_PATH: /testing
  publish-prerelease:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - attach_workspace:
          at: .
      - restore-cache:
          keys:
            - nuget-cache-{{ .Branch }}
      - checkout
      - run:
          name: push package
          command: |
            version="2.0.${CIRCLE_BUILD_NUM}${SUFFIX}"
            dotnet pack -c release -o . /p:PackageVersion="${version}"
            dotnet nuget push -s https://nuget.org -k $nugetapikey ./AwsSecretReader/*.nupkg
          environment:
            SUFFIX: -alpha
  publish-prod:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - attach_workspace:
          at: .
      - restore-cache:
          keys:
            - nuget-cache-{{ .Branch }}
      - checkout
      - run:
          name: push package
          command: |
            version="${CIRCLE_TAG}"
            dotnet pack -c release -o . /p:PackageVersion="${version}"
            dotnet nuget push -s https://nuget.org -k $nugetapikey ./AwsSecretReader/*.nupkg
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - restore
      - unit-tests:
          requires:
            - restore
      - integration-tests:
          requires:
            - restore
      - publish-prerelease:
          requires:
            - unit-tests
            - integration-tests
          filters:
            branches:
              ignore:
                - /master/
      - publish-prod:
          requires:
            - unit-tests
            - integration-tests
          filters:
            tags:
              only: /^3\.1\.[0-999]*/ #Semver version to be published as a production package
            branches:
              ignore: /.*/            
