version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
          name: build package
          command: |
            dotnet restore
            dotnet pack -c release -o . /p:PackageVersion="1.0.${CIRCLE_BUILD_NUM}"
            
      - store_artifacts:
          path: artifacts
      - persist_to_workspace:
          root: .
          paths:
            - .
  unit-tests:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
          name: run unit tests
          command: |
            dotnet restore
            dotnet test ./SecretReaderTests/SecretReaderTests.csproj
  integration-tests:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
          name: run unit tests
          command: |
            dotnet restore
            dotnet test ./SsmIntegrationTest/SsmIntegrationTest.csproj
  publish:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - attach_workspace:
          at: .
      - run:
          name: push package
          command: |
            dotnet nuget push -s https://nuget.org -k $nugetapikey ./AwsSecretReader/*.nupkg
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              ignore:
                - /destroy/
                - /finish.*/
      - unit-tests:
          requires:
            - build
          filters:
            tags:
              ignore:
                - /destroy/
                - /finish.*/
      - integration-tests:
          requires:
            - unit-tests
          filters:
            tags:
              ignore:
                - /destroy/
                - /finish.*/
      - publish:
          requires:
            - build
            - unit-tests
            - integration-tests
          filters:
            tags:
              ignore:
                - /destroy/
                - /finish.*/